import { Inter } from "next/font/google";
import "./globals.css";
import Contextprovider from "./context";
import Navbar from "./components/navbar";






const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        
    
        <Contextprovider>
          <Navbar/>
          <main className="flex min-h-screen flex-col mt-[78px]">{children}</main>
        </Contextprovider>
      
        
        
        </body>
    </html>
  );
}
